name: self update

on:
  schedule:
    - cron: '0 12 * * *'
      timezone: America/New_York
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ github.token }}

      - name: Update Lean package
        id: update
        uses: ./
        with:
          pr: true
          update_lean4_nix: true
          token: ${{ github.token }}
